[[IgnoredVulns]]
id = "GHSA-jpxc-vmjf-9fcj"
# ignoreUntil = 2025-04-01 # Optional exception expiry date
reason = "We do not use Ansible Vault. We use no_log:true where necessary"

# [[IgnoredVulns]]
# id = "GO-2022-1059"
# # ignoreUntil = 2022-11-09 # Optional exception expiry date
# reason = "No external http servers are written in Go lang."
